version: '3.5'

networks:
  default:
    driver: bridge
    name: resultsmanagerptests
    
services:
  selenoid:
    network_mode: bridge
    image: aerokube/selenoid:latest-release
    volumes:
      - "./../../Sources/TestExample/:/etc/selenoid/:rw"
      - "./../../Sources/TestExample/video/:/opt/selenoid/video/:rw"
      - "./../../Sources/TestExample/logs/:/opt/selenoid/logs/:rw"
      - "//var/run/docker.sock:/var/run/docker.sock"
    environment:
      - OVERRIDE_VIDEO_OUTPUT_DIR= ./../../Sources/TestExample/selenoid/video/
    command: ["-limit","4",
              "-video-output-dir", "/opt/selenoid/video/",
              "-log-output-dir", "/opt/selenoid/logs/"]
    ports:
      - "4444:4444"
      
  selenoid-ui:
    network_mode: bridge
    image: "aerokube/selenoid-ui"
    links:
      - selenoid
    ports:
      - "8080:8080"
    command: ["--selenoid-uri", "http://selenoid:4444"]